---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: wego-test-app-q21e1hqs
  namespace: wego-system
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/weaveworks-gitops-test/wego-test-app-q21e1hqs.git

